FROM glottologist/nodejs:19.12.3
ADD README.md .
RUN npm install -g  --unsafe-perm=true --allow-root purescript && \
    npm install -g  --unsafe-perm=true --allow-root pulp bower && \
    npm install -g  --unsafe-perm=true --allow-root spago 


